// Lane 0: main/dominant succession
// Lane 1: northern or secondary parallel states
// Lane 2: southern or tertiary parallel states

const DYNASTIES = [
  // === LANE 0 ===
  { name: "Xia",          zh: "夏",         start: -2070, end: -1600, color: "#4a5566", lane: 0,
    desc: "China's first dynasty, legendary in origin. Yu the Great, famed for taming floods, established hereditary succession." },
  { name: "Shang",        zh: "商",         start: -1600, end: -1046, color: "#6e7f8c", lane: 0,
    desc: "First historically confirmed dynasty. Oracle bone script, advanced bronzeware, and elaborate divination rituals." },
  { name: "W. Zhou",      zh: "西周",       start: -1046, end: -771,  color: "#8d80a0", lane: 0,
    desc: "Established the feudal order and the Mandate of Heaven. Confucians later idealized this era as a golden age." },
  { name: "E. Zhou",      zh: "东周",       start: -771,  end: -221,  color: "#59656f", lane: 0,
    desc: "An era of fragmentation and the Hundred Schools of Thought — Confucius, Laozi, Sunzi, Mencius all lived here." },
  { name: "Qin",          zh: "秦",         start: -221,  end: -206,  color: "#c8a8c4", lane: 0,
    desc: "First unified Chinese empire. Standardized writing, weights, and measures. Built the Great Wall and Terracotta Army." },
  { name: "W. Han",       zh: "西汉",       start: -206,  end: 9,     color: "#ddbdd5", lane: 0,
    desc: "Golden age of early imperial China. The Silk Road opened. Confucianism became state orthodoxy." },
  { name: "Xin",          zh: "新",         start: 9,     end: 23,    color: "#7a8a97", lane: 0,
    desc: "Short-lived dynasty of reformer Wang Mang. Sweeping land reform edicts triggered massive rebellion." },
  { name: "E. Han",       zh: "东汉",       start: 25,    end: 220,   color: "#ac9fbb", lane: 0,
    desc: "Restored Han dynasty. Buddhism arrived from India. Paper was invented by Cai Lun (105 CE)." },
  { name: "Wei",          zh: "魏",         start: 220,   end: 265,   color: "#3d4a58", lane: 0,
    desc: "Strongest of the Three Kingdoms, controlling the north. Founded by Cao Pi, son of the warlord Cao Cao." },
  { name: "W. Jin",       zh: "西晋",       start: 265,   end: 316,   color: "#b3a3c2", lane: 0,
    desc: "Briefly reunified China under Sima Yan. Collapsed after the War of the Eight Princes and nomadic invasions." },
  { name: "N. Dynasties", zh: "北朝",       start: 316,   end: 581,   color: "#4d5e6c", lane: 0,
    desc: "A series of nomadic-founded states in the north: 16 Kingdoms → N. Wei → E./W. Wei → N. Qi/N. Zhou. Sino-nomadic cultural fusion." },
  { name: "Sui",          zh: "隋",         start: 581,   end: 618,   color: "#c0b3cc", lane: 0,
    desc: "Reunified China after 270 years of division. Built the Grand Canal. Collapsed from overextension and failed Korean campaigns." },
  { name: "Tang",         zh: "唐",         start: 618,   end: 907,   color: "#ddbdd5", lane: 0,
    desc: "Cosmopolitan golden age — China's most internationally connected empire. Poetry, art, and the Silk Road at their peak." },
  { name: "5 Dynasties",  zh: "五代十国",   start: 907,   end: 960,   color: "#59656f", lane: 0,
    desc: "Five short-lived northern dynasties and ten independent southern states after Tang's collapse. 53 years of fragmentation." },
  { name: "N. Song",      zh: "北宋",       start: 960,   end: 1127,  color: "#ac9fbb", lane: 0,
    desc: "Economic revolution: movable type, paper money, gunpowder weapons. Lost the north to the Jurchen Jin in 1127." },
  { name: "S. Song",      zh: "南宋",       start: 1127,  end: 1279,  color: "#8d80a0", lane: 0,
    desc: "Retreated south of the Huai River. High culture, commerce, and maritime trade. Fell to the Mongols at the Battle of Yamen." },
  { name: "Yuan",         zh: "元",         start: 1271,  end: 1368,  color: "#3a4855", lane: 0,
    desc: "Mongol dynasty of Kublai Khan. Connected China to the vast Mongol Empire; Marco Polo visited this court." },
  { name: "Ming",         zh: "明",         start: 1368,  end: 1644,  color: "#c4adc0", lane: 0,
    desc: "Rebuilt the Great Wall. Zheng He's ocean voyages reached Africa. The Forbidden City was completed in 1420." },
  { name: "Qing",         zh: "清",         start: 1644,  end: 1912,  color: "#ddbdd5", lane: 0,
    desc: "Manchu dynasty and China's last imperial house. Expanded to greatest territorial extent; declined under Western pressure." },
  { name: "ROC",          zh: "中华民国",   start: 1912,  end: 1949,  color: "#7a8f9b", lane: 0,
    desc: "Republic founded after Qing abdication. Warlord era, Japanese invasion, and Civil War led to retreat to Taiwan in 1949." },
  { name: "PRC",          zh: "中华人民共和国", start: 1949, end: 2025, color: "#9585a8", lane: 0,
    desc: "People's Republic founded by Mao Zedong. Great Leap Forward, Cultural Revolution, Reform & Opening Up, rise to global power." },

  // === LANE 1: secondary / parallel states ===
  { name: "Shu Han",      zh: "蜀汉",       start: 221,   end: 263,   color: "#7a6e88", lane: 1,
    desc: "Kingdom in Sichuan that claimed Han legitimacy. Led by Liu Bei and his chancellor Zhuge Liang." },
  { name: "E. Jin",       zh: "东晋",       start: 317,   end: 420,   color: "#6e7f8c", lane: 1,
    desc: "Southern rump state after northern Jin fell to nomads. Cultural refinement flourished in Jiankang (Nanjing)." },
  { name: "S. Dynasties", zh: "南朝",       start: 420,   end: 589,   color: "#8d80a0", lane: 1,
    desc: "Four successive Han Chinese dynasties in the south (Liu Song, S. Qi, Liang, Chen). Literary and artistic golden age." },
  { name: "Liao",         zh: "辽",         start: 916,   end: 1125,  color: "#59656f", lane: 1,
    desc: "Khitan empire controlling Manchuria, Inner Mongolia, and the Sixteen Prefectures near Beijing. Coexisted with Song." },

  // === LANE 2: tertiary / further parallel states ===
  { name: "Wu",           zh: "吴",         start: 222,   end: 280,   color: "#4d5e6c", lane: 2,
    desc: "Maritime Three Kingdoms state controlling the Yangtze Delta. Known for naval power and the Battle of Red Cliffs." },
  { name: "Jin (Jurchen)",zh: "金",         start: 1115,  end: 1234,  color: "#3d4a58", lane: 2,
    desc: "Jurchen empire that conquered the Liao and northern China (capturing Kaifeng in 1127). Later crushed by Mongols." },
];

const EVENT_CATEGORIES = {
  political:    { color: "#ddbdd5", label: "Political" },
  military:     { color: "#ac9fbb", label: "Military" },
  culture:      { color: "#c8bdd0", label: "Culture" },
  invention:    { color: "#7a8f9b", label: "Invention" },
  trade:        { color: "#f7ebec", label: "Trade" },
  construction: { color: "#8d80a0", label: "Construction" },
};

const EVENTS = [
  { year: -2070, title: "Xia Dynasty Founded",           dynasty: "Xia",      cat: "political",
    desc: "Yu the Great, legendary flood-tamer, founds the Xia dynasty and establishes hereditary succession — a pivotal shift from elective chieftainship." },
  { year: -1600, title: "Shang Dynasty Founded",         dynasty: "Shang",    cat: "political",
    desc: "Tang of Shang overthrows the last Xia king at the Battle of Mingtiao, establishing the Shang with its capital later at Yin (modern Anyang)." },
  { year: -1250, title: "Oracle Bone Writing",           dynasty: "Shang",    cat: "culture",
    desc: "Oracle bone inscriptions emerge as the earliest confirmed Chinese writing, used by Shang kings for divination about harvests, war, and royal health." },
  { year: -1046, title: "Battle of Muye",                dynasty: "W. Zhou",  cat: "military",
    desc: "King Wu of Zhou defeats the Shang at Muye. The Zhou establish the Mandate of Heaven doctrine to legitimize dynastic transitions." },
  { year: -771,  title: "Zhou Capital Sacked",           dynasty: "E. Zhou",  cat: "military",
    desc: "Rong nomads sack the Zhou capital Hao, killing King You. The Zhou flee east to Luoyi, beginning the weakened Eastern Zhou period." },
  { year: -551,  title: "Confucius Born",                dynasty: "E. Zhou",  cat: "culture",
    desc: "Kong Qiu (Confucius) born in the state of Lu. His teachings on ethics, ritual, and governance would shape Chinese civilization for 2,500 years." },
  { year: -500,  title: "Laozi & Daoism",                dynasty: "E. Zhou",  cat: "culture",
    desc: "Laozi, legendary author of the Tao Te Ching, lives during this era. His philosophy of natural harmony and non-action (wu-wei) founds Daoism." },
  { year: -496,  title: "Art of War Written",            dynasty: "E. Zhou",  cat: "culture",
    desc: "Sunzi composes 'The Art of War', a 13-chapter military treatise still studied by strategists, business leaders, and generals worldwide." },
  { year: -403,  title: "Warring States Period Begins",  dynasty: "E. Zhou",  cat: "political",
    desc: "The three-way partition of Jin is formally recognized, marking the Warring States era — seven major kingdoms in constant, devastating conflict." },
  { year: -256,  title: "Zhou Dynasty Ends",             dynasty: "E. Zhou",  cat: "political",
    desc: "The last Zhou king surrenders to Qin. The 800-year Zhou dynasty collapses, leaving Qin as the undisputed hegemon." },
  { year: -221,  title: "Qin Unification",               dynasty: "Qin",      cat: "political",
    desc: "Ying Zheng conquers the last rival kingdom and declares himself 'Qin Shi Huang' — First Emperor of China — creating the first unified empire." },
  { year: -215,  title: "Great Wall Construction",       dynasty: "Qin",      cat: "construction",
    desc: "Qin Shi Huang orders existing walls connected into one Great Wall using 300,000 soldiers and 500,000 laborers to defend against Xiongnu raids." },
  { year: -213,  title: "Burning of Books",              dynasty: "Qin",      cat: "political",
    desc: "Chancellor Li Si advises burning Confucian and historical books outside the Qin canon, and burying 460 scholars alive, to suppress dissent." },
  { year: -210,  title: "Terracotta Army Completed",     dynasty: "Qin",      cat: "construction",
    desc: "Qin Shi Huang's massive mausoleum complex, including 8,000 life-sized terracotta soldiers, chariots, and horses, is completed near Xi'an." },
  { year: -209,  title: "Chen Sheng Uprising",           dynasty: "Qin",      cat: "military",
    desc: "Chen Sheng and Wu Guang lead China's first major peasant rebellion. Their uprising ignites the broader revolt that topples the Qin dynasty." },
  { year: -206,  title: "Han Dynasty Founded",           dynasty: "W. Han",   cat: "political",
    desc: "Liu Bang defeats rival Xiang Yu and establishes the Han dynasty as Emperor Gaozu — the dynasty so foundational that Chinese people call themselves 'Han people'." },
  { year: -138,  title: "Silk Road Opens",               dynasty: "W. Han",   cat: "trade",
    desc: "Emperor Wu sends diplomat Zhang Qian west, establishing the Silk Road — a network linking China to Central Asia, Persia, and Rome." },
  { year: -119,  title: "Han-Xiongnu Campaigns",         dynasty: "W. Han",   cat: "military",
    desc: "Generals Wei Qing and Huo Qubing lead massive campaigns deep into the Gobi, pushing the Xiongnu north and securing Han's northern frontier." },
  { year: -104,  title: "Shiji Completed",               dynasty: "W. Han",   cat: "culture",
    desc: "Sima Qian completes the Shiji (Records of the Grand Historian), China's first comprehensive history covering 2,500 years — written despite castration as punishment." },
  { year: 9,     title: "Wang Mang's Usurpation",        dynasty: "Xin",      cat: "political",
    desc: "Wang Mang deposes the infant Han emperor and proclaims the Xin dynasty, attempting radical land redistribution and currency reform." },
  { year: 105,   title: "Paper Invented",                dynasty: "E. Han",   cat: "invention",
    desc: "Cai Lun refines and standardizes papermaking from bark, hemp, and rags. Paper transforms communication, administration, and eventually global civilization." },
  { year: 132,   title: "Seismoscope Invented",          dynasty: "E. Han",   cat: "invention",
    desc: "Zhang Heng invents the world's first seismoscope, capable of detecting distant earthquakes by dropping a bronze ball from a dragon's mouth." },
  { year: 184,   title: "Yellow Turban Rebellion",       dynasty: "E. Han",   cat: "military",
    desc: "Daoist healer Zhang Jue leads a massive peasant uprising under the Yellow Turban banner, fatally weakening the Han and enabling warlord fragmentation." },
  { year: 208,   title: "Battle of Red Cliffs",          dynasty: "E. Han",   cat: "military",
    desc: "Cao Cao's northern fleet is burned by Sun Quan and Liu Bei's allies in a decisive naval battle, ensuring the Three Kingdoms split and reshaping Chinese history." },
  { year: 220,   title: "Three Kingdoms Begin",          dynasty: "Wei",      cat: "political",
    desc: "Cao Pi deposes the last Han emperor and proclaims Wei. Liu Bei and Sun Quan soon follow, creating three rival kingdoms. The Romance of the Three Kingdoms immortalizes this era." },
  { year: 265,   title: "Jin Reunification",             dynasty: "W. Jin",   cat: "political",
    desc: "Sima Yan founds the Jin dynasty and conquers Wu in 280, briefly reunifying China for the first time since Han." },
  { year: 316,   title: "Northern China Falls",          dynasty: "N. Dynasties", cat: "military",
    desc: "Xiongnu forces sack Luoyang and Chang'an. The Jin court flees south, beginning the Eastern Jin and nearly three centuries of north-south division." },
  { year: 399,   title: "Faxian's Pilgrimage to India",  dynasty: "E. Jin",   cat: "culture",
    desc: "Monk Faxian walks overland to India and returns by sea to collect Buddhist scriptures — one of the most remarkable journeys of the ancient world." },
  { year: 494,   title: "N. Wei Sinicization Decree",   dynasty: "N. Dynasties", cat: "political",
    desc: "Emperor Xiaowen of Northern Wei moves the capital to Luoyang and mandates Chinese dress, language, and names for the Xianbei — a landmark of cultural assimilation." },
  { year: 581,   title: "Sui Reunification",             dynasty: "Sui",      cat: "political",
    desc: "Yang Jian (Emperor Wen) founds Sui and reunifies China for the first time in nearly 400 years, ending the north-south division." },
  { year: 605,   title: "Grand Canal Built",             dynasty: "Sui",      cat: "construction",
    desc: "Emperor Yang orders the Grand Canal, linking the Yellow and Yangtze rivers over 1,700 km. Over a million laborers were conscripted. Still in use today." },
  { year: 612,   title: "Goguryeo Campaign Fails",       dynasty: "Sui",      cat: "military",
    desc: "Sui's catastrophic invasion of the Korean kingdom of Goguryeo. Over a million soldiers mobilized; massive defeat triggers rebellions that destroy the dynasty." },
  { year: 618,   title: "Tang Dynasty Founded",          dynasty: "Tang",     cat: "political",
    desc: "Li Yuan, Duke of Tang, overthrows the Sui as Emperor Gaozu. His son Li Shimin (Emperor Taizong) soon creates one of China's greatest reigns." },
  { year: 629,   title: "Xuanzang's Journey to India",   dynasty: "Tang",     cat: "culture",
    desc: "Monk Xuanzang travels secretly overland to India for Buddhist scriptures, returning after 17 years. His journey inspired the classic novel Journey to the West." },
  { year: 690,   title: "Empress Wu Zetian",             dynasty: "Tang",     cat: "political",
    desc: "Wu Zetian declares herself Emperor of the Zhou — the only woman in Chinese history to assume the title of empress regnant, ruling effectively for decades." },
  { year: 751,   title: "Battle of Talas",               dynasty: "Tang",     cat: "military",
    desc: "Tang forces defeated by the Abbasid Caliphate at Talas River. Captured Tang soldiers transmit papermaking technology to the Islamic world and eventually Europe." },
  { year: 755,   title: "An Lushan Rebellion",           dynasty: "Tang",     cat: "military",
    desc: "General An Lushan rebels and sacks Chang'an. The devastating eight-year war kills tens of millions and the Tang never fully recovers its former glory." },
  { year: 868,   title: "Diamond Sutra Printed",         dynasty: "Tang",     cat: "culture",
    desc: "The Diamond Sutra (868 CE) is printed using woodblock printing — the oldest dated printed book in existence, discovered in the Dunhuang cave manuscripts." },
  { year: 907,   title: "Tang Falls",                    dynasty: "5 Dynasties", cat: "political",
    desc: "Warlord Zhu Wen deposes the last Tang emperor. China fragments into the Five Dynasties in the north and Ten Kingdoms in the south for 53 years." },
  { year: 960,   title: "Song Dynasty Founded",          dynasty: "N. Song",  cat: "political",
    desc: "General Zhao Kuangyin is acclaimed emperor by his soldiers in the 'Yellow Robe Incident', founding the Song dynasty through a near-bloodless coup." },
  { year: 1040,  title: "Movable Type Invented",         dynasty: "N. Song",  cat: "invention",
    desc: "Bi Sheng invents movable type printing with fired ceramic characters — four centuries before Gutenberg, transforming the spread of knowledge in East Asia." },
  { year: 1069,  title: "Wang Anshi's New Policies",     dynasty: "N. Song",  cat: "political",
    desc: "Grand Chancellor Wang Anshi implements sweeping fiscal, military, and agricultural reforms, sparking one of China's most intense political factional battles." },
  { year: 1115,  title: "Jin Dynasty Founded",           dynasty: "Jin (Jurchen)", cat: "political",
    desc: "Wanyan Aguda unites the Jurchen tribes and founds the Jin dynasty, beginning their conquest of the Liao and eventual takeover of northern China." },
  { year: 1127,  title: "Fall of Northern Song",         dynasty: "S. Song",  cat: "military",
    desc: "Jin forces capture the Song capital Kaifeng and take Emperor Huizong and Emperor Qinzong prisoner. The 'Jingkang Incident' — the Song court's greatest humiliation." },
  { year: 1215,  title: "Mongols Take Beijing",          dynasty: "Jin (Jurchen)", cat: "military",
    desc: "Genghis Khan's forces sack Zhongdu (Beijing) after a long siege, dealing a devastating blow to the Jurchen Jin dynasty." },
  { year: 1271,  title: "Yuan Dynasty Founded",          dynasty: "Yuan",     cat: "political",
    desc: "Kublai Khan renames the Mongol domain 'Yuan', establishing a Chinese-style dynasty while ruling from Khanbaliq (Beijing)." },
  { year: 1275,  title: "Marco Polo Arrives",            dynasty: "Yuan",     cat: "trade",
    desc: "Venetian merchant Marco Polo arrives at Kublai Khan's court and spends 17 years in China. His later accounts introduce a dazzling China to medieval Europe." },
  { year: 1279,  title: "Mongol Conquest Complete",      dynasty: "Yuan",     cat: "military",
    desc: "Battle of Yamen: the last Song loyalists are crushed. Prime Minister Lu Xiufu leaps into the sea carrying the child emperor. China is fully under Mongol rule." },
  { year: 1351,  title: "Red Turban Rebellion",          dynasty: "Yuan",     cat: "military",
    desc: "White Lotus Society uprising against Mongol rule. Zhu Yuanzhang, a peasant orphan turned monk, rises to lead the rebellion that founds the Ming." },
  { year: 1368,  title: "Ming Dynasty Founded",          dynasty: "Ming",     cat: "political",
    desc: "Zhu Yuanzhang expels the Mongols and founds the Ming dynasty as the Hongwu Emperor, rising from abject poverty to rule the world's largest empire." },
  { year: 1405,  title: "Zheng He's Voyages Begin",      dynasty: "Ming",     cat: "trade",
    desc: "Admiral Zheng He leads the first of seven massive treasure fleet expeditions, reaching Southeast Asia, India, Arabia, and East Africa with ships dwarfing Columbus's." },
  { year: 1420,  title: "Forbidden City Completed",      dynasty: "Ming",     cat: "construction",
    desc: "The Forbidden City (Palace Museum) in Beijing is completed after 14 years of construction using a million laborers. It served as the imperial palace for 500 years." },
  { year: 1449,  title: "Tumu Crisis",                   dynasty: "Ming",     cat: "military",
    desc: "Emperor Zhengtong is captured by Oirat Mongols at Tumu — an emperor taken prisoner in battle. The court crowns a new emperor and successfully defends Beijing." },
  { year: 1582,  title: "Matteo Ricci in China",         dynasty: "Ming",     cat: "culture",
    desc: "Jesuit missionary Matteo Ricci arrives in China, mastering classical Chinese and eventually gaining access to the imperial court, beginning a major cultural exchange." },
  { year: 1644,  title: "Fall of Ming / Qing Conquest",  dynasty: "Qing",     cat: "political",
    desc: "Rebel Li Zicheng captures Beijing; Emperor Chongzhen hangs himself. Manchu forces enter through the Great Wall and establish the Qing dynasty." },
  { year: 1661,  title: "Kangxi Emperor's Reign",        dynasty: "Qing",     cat: "political",
    desc: "The Kangxi Emperor begins his 61-year reign — the longest confirmed reign of any Chinese emperor — marked by military campaigns and the great Kangxi Dictionary." },
  { year: 1683,  title: "Taiwan Annexed",                dynasty: "Qing",     cat: "political",
    desc: "Qing forces defeat the Ming loyalist Kingdom of Tungning, bringing Taiwan under Chinese imperial control for the first time in history." },
  { year: 1793,  title: "Macartney Mission Rejected",    dynasty: "Qing",     cat: "trade",
    desc: "British envoy Macartney seeks expanded trade; Emperor Qianlong famously replies that China 'possesses all things' and has no need for foreign goods." },
  { year: 1839,  title: "First Opium War",               dynasty: "Qing",     cat: "military",
    desc: "Commissioner Lin Zexu destroys 1,200 tons of British opium. Britain retaliates militarily, beginning the 'Century of Humiliation' and the era of unequal treaties." },
  { year: 1842,  title: "Treaty of Nanking",             dynasty: "Qing",     cat: "political",
    desc: "China's first 'unequal treaty' cedes Hong Kong Island to Britain and opens five treaty ports. The model for a series of humiliating concessions to follow." },
  { year: 1850,  title: "Taiping Heavenly Kingdom",      dynasty: "Qing",     cat: "military",
    desc: "Hong Xiuquan, who believed himself Jesus's younger brother, establishes a Christian theocracy in southern China. The ensuing war kills 20–30 million people." },
  { year: 1860,  title: "Old Summer Palace Burned",      dynasty: "Qing",     cat: "military",
    desc: "Anglo-French forces burn and loot the Old Summer Palace (Yuanmingyuan) during the Second Opium War. The ruins remain a symbol of national humiliation." },
  { year: 1894,  title: "First Sino-Japanese War",       dynasty: "Qing",     cat: "military",
    desc: "China is decisively defeated by Meiji Japan, ceding Taiwan and paying massive reparations. The defeat shocks China and accelerates reform movements." },
  { year: 1898,  title: "Hundred Days Reform",           dynasty: "Qing",     cat: "political",
    desc: "Emperor Guangxu issues sweeping modernization edicts. Empress Dowager Cixi stages a coup after 103 days, imprisoning him and executing reformers." },
  { year: 1900,  title: "Boxer Rebellion",               dynasty: "Qing",     cat: "military",
    desc: "Anti-foreign Boxer uprising supported by Empress Dowager Cixi. Eight-nation alliance invades, occupies Beijing, and forces the Boxer Protocol — another humiliation." },
  { year: 1905,  title: "Imperial Exam Abolished",       dynasty: "Qing",     cat: "political",
    desc: "The 1,300-year-old imperial examination system is abolished. The backbone of China's civil service and Confucian social order disappears overnight." },
  { year: 1911,  title: "Xinhai Revolution",             dynasty: "ROC",      cat: "political",
    desc: "The Wuchang Uprising triggers nationwide revolt. Sun Yat-sen is proclaimed provisional president; provinces declare independence and the Qing dynasty collapses." },
  { year: 1912,  title: "Republic Founded",              dynasty: "ROC",      cat: "political",
    desc: "The Republic of China is proclaimed on January 1. Last emperor Puyi abdicates on February 12, ending over 2,000 years of imperial rule." },
  { year: 1919,  title: "May Fourth Movement",           dynasty: "ROC",      cat: "culture",
    desc: "Student protests against the Versailles Treaty spark a sweeping cultural revolution: rejection of Confucian tradition, embrace of science, democracy, and vernacular literature." },
  { year: 1921,  title: "CCP Founded",                   dynasty: "ROC",      cat: "political",
    desc: "The Chinese Communist Party is founded in Shanghai with 13 delegates, including a young Mao Zedong. Chen Duxiu becomes first General Secretary." },
  { year: 1927,  title: "Shanghai Massacre",             dynasty: "ROC",      cat: "political",
    desc: "Chiang Kai-shek's Nationalists massacre thousands of Communist Party members in Shanghai, permanently fracturing the first United Front and starting the Civil War." },
  { year: 1931,  title: "Japan Invades Manchuria",       dynasty: "ROC",      cat: "military",
    desc: "The Mukden Incident: Japanese officers blow up their own railway to justify invading Manchuria, establishing the Manchukuo puppet state." },
  { year: 1934,  title: "The Long March",                dynasty: "ROC",      cat: "military",
    desc: "Communist forces make an epic 6,000-mile retreat across China to escape Nationalist encirclement. Mao Zedong emerges as undisputed leader of the CCP." },
  { year: 1937,  title: "Second Sino-Japanese War",      dynasty: "ROC",      cat: "military",
    desc: "Full-scale Japanese invasion begins. The Nanjing Massacre kills an estimated 200,000–300,000 civilians and POWs. China endures eight years of brutal occupation." },
  { year: 1945,  title: "Japan Surrenders",              dynasty: "ROC",      cat: "military",
    desc: "Japan surrenders following the atomic bombs and Soviet entry into the Pacific War. Taiwan returns to Chinese control after 50 years of Japanese colonial rule." },
  { year: 1949,  title: "PRC Founded",                   dynasty: "PRC",      cat: "political",
    desc: "Mao Zedong proclaims the People's Republic of China from Tiananmen Gate on October 1. The Nationalist government retreats to Taiwan." },
  { year: 1950,  title: "Korean War Entry",              dynasty: "PRC",      cat: "military",
    desc: "China sends 'volunteer' forces to Korea, pushing UN forces back from the Yalu River in a surprising display of military power. Over 180,000 Chinese casualties." },
  { year: 1958,  title: "Great Leap Forward",            dynasty: "PRC",      cat: "political",
    desc: "Mao's rapid industrialization and collectivization campaign causes the Great Chinese Famine — historians estimate 15–55 million deaths from starvation." },
  { year: 1964,  title: "China Tests Nuclear Bomb",      dynasty: "PRC",      cat: "political",
    desc: "China's first successful nuclear weapons test makes it the fifth nuclear power, dramatically altering the Cold War balance of power in Asia." },
  { year: 1966,  title: "Cultural Revolution Begins",    dynasty: "PRC",      cat: "political",
    desc: "Mao launches the Cultural Revolution to purge rivals and reassert control. Red Guards destroy temples, artworks, and persecute millions of intellectuals." },
  { year: 1972,  title: "Nixon Visits China",            dynasty: "PRC",      cat: "trade",
    desc: "US President Nixon's historic week-long visit ends 23 years of estrangement and reshapes Cold War geopolitics, isolating the Soviet Union." },
  { year: 1976,  title: "Mao Zedong Dies",               dynasty: "PRC",      cat: "political",
    desc: "Mao dies at 82. Hua Guofeng arrests the Gang of Four within weeks. Deng Xiaoping gradually rises to power, pivoting China toward pragmatic reform." },
  { year: 1978,  title: "Reform & Opening Up",           dynasty: "PRC",      cat: "political",
    desc: "Deng Xiaoping launches market reforms and creates Special Economic Zones. China begins its transformation from a closed communist state into an economic powerhouse." },
  { year: 1989,  title: "Tiananmen Square",              dynasty: "PRC",      cat: "political",
    desc: "Student-led democracy protests gather in Beijing and dozens of cities. Military crackdown on June 4th kills hundreds to thousands and reshapes China's political trajectory." },
  { year: 1997,  title: "Hong Kong Handover",            dynasty: "PRC",      cat: "political",
    desc: "Britain transfers Hong Kong to China under 'one country, two systems', ending 156 years of British colonial rule. Macau follows in 1999." },
  { year: 2001,  title: "China Joins WTO",               dynasty: "PRC",      cat: "trade",
    desc: "China joins the World Trade Organization, accelerating its integration into the global economy and triggering the most rapid economic expansion in history." },
  { year: 2008,  title: "Beijing Olympics",              dynasty: "PRC",      cat: "culture",
    desc: "China hosts the Summer Olympics with a spectacular opening ceremony watched by 1 billion people, announcing its emergence as a global superpower." },
  { year: 2013,  title: "Belt & Road Initiative",        dynasty: "PRC",      cat: "trade",
    desc: "Xi Jinping announces the Belt and Road Initiative — a trillion-dollar global infrastructure investment program spanning 140+ countries, reviving the ancient Silk Road concept." },
  { year: 2020,  title: "COVID-19 Pandemic",             dynasty: "PRC",      cat: "political",
    desc: "COVID-19 emerges in Wuhan and spreads to become the worst global pandemic since 1918. China implements strict lockdowns; global death toll exceeds 7 million." },
];
