// Lane 0: main/dominant succession
// Lane 1: northern or secondary parallel states
// Lane 2: southern or tertiary parallel states

const DYNASTIES = [
  // === LANE 0 ===
  { name: "Xia",          zh: "夏",         start: -2070, end: -1600, color: "#4a5566", lane: 0,
    desc: "China's first dynasty, legendary in origin. Yu the Great, famed for taming floods, established hereditary succession." },
  { name: "Shang",        zh: "商",         start: -1600, end: -1046, color: "#6e7f8c", lane: 0,
    desc: "First historically confirmed dynasty. Oracle bone script, advanced bronzeware, and elaborate divination rituals." },
  { name: "W. Zhou",      zh: "西周",       start: -1046, end: -771,  color: "#8d80a0", lane: 0,
    desc: "Established the feudal order and the Mandate of Heaven. Confucians later idealized this era as a golden age." },
  { name: "E. Zhou",      zh: "东周",       start: -771,  end: -221,  color: "#59656f", lane: 0,
    desc: "An era of fragmentation and the Hundred Schools of Thought — Confucius, Laozi, Sunzi, Mencius all lived here." },
  { name: "Qin",          zh: "秦",         start: -221,  end: -206,  color: "#c8a8c4", lane: 0,
    desc: "First unified Chinese empire. Standardized writing, weights, and measures. Built the Great Wall and Terracotta Army." },
  { name: "W. Han",       zh: "西汉",       start: -206,  end: 9,     color: "#ddbdd5", lane: 0,
    desc: "Golden age of early imperial China. The Silk Road opened. Confucianism became state orthodoxy." },
  { name: "Xin",          zh: "新",         start: 9,     end: 23,    color: "#7a8a97", lane: 0,
    desc: "Short-lived dynasty of reformer Wang Mang. Sweeping land reform edicts triggered massive rebellion." },
  { name: "E. Han",       zh: "东汉",       start: 25,    end: 220,   color: "#ac9fbb", lane: 0,
    desc: "Restored Han dynasty. Buddhism arrived from India. Paper was invented by Cai Lun (105 CE)." },
  { name: "Wei",          zh: "魏",         start: 220,   end: 265,   color: "#3d4a58", lane: 0,
    desc: "Strongest of the Three Kingdoms, controlling the north. Founded by Cao Pi, son of the warlord Cao Cao." },
  { name: "W. Jin",       zh: "西晋",       start: 265,   end: 316,   color: "#b3a3c2", lane: 0,
    desc: "Briefly reunified China under Sima Yan. Collapsed after the War of the Eight Princes and nomadic invasions." },
  { name: "N. Dynasties", zh: "北朝",       start: 316,   end: 581,   color: "#4d5e6c", lane: 0,
    desc: "A series of nomadic-founded states in the north: 16 Kingdoms → N. Wei → E./W. Wei → N. Qi/N. Zhou. Sino-nomadic cultural fusion." },
  { name: "Sui",          zh: "隋",         start: 581,   end: 618,   color: "#c0b3cc", lane: 0,
    desc: "Reunified China after 270 years of division. Built the Grand Canal. Collapsed from overextension and failed Korean campaigns." },
  { name: "Tang",         zh: "唐",         start: 618,   end: 907,   color: "#ddbdd5", lane: 0,
    desc: "Cosmopolitan golden age — China's most internationally connected empire. Poetry, art, and the Silk Road at their peak." },
  { name: "5 Dynasties",  zh: "五代十国",   start: 907,   end: 960,   color: "#59656f", lane: 0,
    desc: "Five short-lived northern dynasties and ten independent southern states after Tang's collapse. 53 years of fragmentation." },
  { name: "N. Song",      zh: "北宋",       start: 960,   end: 1127,  color: "#ac9fbb", lane: 0,
    desc: "Economic revolution: movable type, paper money, gunpowder weapons. Lost the north to the Jurchen Jin in 1127." },
  { name: "S. Song",      zh: "南宋",       start: 1127,  end: 1279,  color: "#8d80a0", lane: 0,
    desc: "Retreated south of the Huai River. High culture, commerce, and maritime trade. Fell to the Mongols at the Battle of Yamen." },
  { name: "Yuan",         zh: "元",         start: 1271,  end: 1368,  color: "#3a4855", lane: 0,
    desc: "Mongol dynasty of Kublai Khan. Connected China to the vast Mongol Empire; Marco Polo visited this court." },
  { name: "Ming",         zh: "明",         start: 1368,  end: 1644,  color: "#c4adc0", lane: 0,
    desc: "Rebuilt the Great Wall. Zheng He's ocean voyages reached Africa. The Forbidden City was completed in 1420." },
  { name: "Qing",         zh: "清",         start: 1644,  end: 1912,  color: "#ddbdd5", lane: 0,
    desc: "Manchu dynasty and China's last imperial house. Expanded to greatest territorial extent; declined under Western pressure." },
  { name: "ROC",          zh: "中华民国",   start: 1912,  end: 1949,  color: "#7a8f9b", lane: 0,
    desc: "Republic founded after Qing abdication. Warlord era, Japanese invasion, and Civil War led to retreat to Taiwan in 1949." },
  { name: "PRC",          zh: "中华人民共和国", start: 1949, end: 2025, color: "#9585a8", lane: 0,
    desc: "People's Republic founded by Mao Zedong. Great Leap Forward, Cultural Revolution, Reform & Opening Up, rise to global power." },

  // === LANE 1: secondary / parallel states ===
  { name: "Shu Han",      zh: "蜀汉",       start: 221,   end: 263,   color: "#7a6e88", lane: 1,
    desc: "Kingdom in Sichuan that claimed Han legitimacy. Led by Liu Bei and his chancellor Zhuge Liang." },
  { name: "E. Jin",       zh: "东晋",       start: 317,   end: 420,   color: "#6e7f8c", lane: 1,
    desc: "Southern rump state after northern Jin fell to nomads. Cultural refinement flourished in Jiankang (Nanjing)." },
  { name: "S. Dynasties", zh: "南朝",       start: 420,   end: 589,   color: "#8d80a0", lane: 1,
    desc: "Four successive Han Chinese dynasties in the south (Liu Song, S. Qi, Liang, Chen). Literary and artistic golden age." },
  { name: "Liao",         zh: "辽",         start: 916,   end: 1125,  color: "#59656f", lane: 1,
    desc: "Khitan empire controlling Manchuria, Inner Mongolia, and the Sixteen Prefectures near Beijing. Coexisted with Song." },

  // === LANE 2: tertiary / further parallel states ===
  { name: "Wu",           zh: "吴",         start: 222,   end: 280,   color: "#4d5e6c", lane: 2,
    desc: "Maritime Three Kingdoms state controlling the Yangtze Delta. Known for naval power and the Battle of Red Cliffs." },
  { name: "Jin (Jurchen)",zh: "金",         start: 1115,  end: 1234,  color: "#3d4a58", lane: 2,
    desc: "Jurchen empire that conquered the Liao and northern China (capturing Kaifeng in 1127). Later crushed by Mongols." },
];

const EVENT_CATEGORIES = {
  political:    { color: "#ddbdd5", label: "Political" },
  military:     { color: "#ac9fbb", label: "Military" },
  culture:      { color: "#c8bdd0", label: "Culture" },
  invention:    { color: "#7a8f9b", label: "Invention" },
  trade:        { color: "#f7ebec", label: "Trade" },
  construction: { color: "#8d80a0", label: "Construction" },
};

const EVENTS = [
  { year: -2070, title: "Xia Dynasty Founded",          titleZh: "夏朝建立",         dynasty: "Xia",           cat: "political",
    desc: "Yu the Great, legendary flood-tamer, founds the Xia dynasty and establishes hereditary succession — a pivotal shift from elective chieftainship.",
    descZh: "传说中的治水英雄大禹建立夏朝，开创世袭制度，中国就此迈入王朝时代。" },
  { year: -1600, title: "Shang Dynasty Founded",        titleZh: "商朝建立",         dynasty: "Shang",         cat: "political",
    desc: "Tang of Shang overthrows the last Xia king at the Battle of Mingtiao, establishing the Shang with its capital later at Yin (modern Anyang).",
    descZh: "商汤于鸣条之战击败夏桀，建立商朝，都城后迁至殷（今安阳）。" },
  { year: -1250, title: "Oracle Bone Writing",          titleZh: "甲骨文",           dynasty: "Shang",         cat: "culture",
    desc: "Oracle bone inscriptions emerge as the earliest confirmed Chinese writing, used by Shang kings for divination about harvests, war, and royal health.",
    descZh: "商王祭祀占卜时所用的龟甲兽骨上刻有文字，是中国已知最早的成熟文字系统。" },
  { year: -1046, title: "Battle of Muye",               titleZh: "牧野之战",         dynasty: "W. Zhou",       cat: "military",
    desc: "King Wu of Zhou defeats the Shang at Muye. The Zhou establish the Mandate of Heaven doctrine to legitimize dynastic transitions.",
    descZh: "周武王于牧野大败商纣王，建立周朝，并提出「天命」学说以正统治合法性。" },
  { year: -771,  title: "Zhou Capital Sacked",          titleZh: "周都被攻陷",       dynasty: "E. Zhou",       cat: "military",
    desc: "Rong nomads sack the Zhou capital Hao, killing King You. The Zhou flee east to Luoyi, beginning the weakened Eastern Zhou period.",
    descZh: "戎族攻破镐京，周幽王被杀，周室东迁洛邑，进入势力衰微的东周时期。" },
  { year: -551,  title: "Confucius Born",               titleZh: "孔子诞生",         dynasty: "E. Zhou",       cat: "culture",
    desc: "Kong Qiu (Confucius) born in the state of Lu. His teachings on ethics, ritual, and governance would shape Chinese civilization for 2,500 years.",
    descZh: "孔丘（孔子）生于鲁国，其关于道德、礼制与治国的思想影响中华文明长达两千五百年。" },
  { year: -500,  title: "Laozi & Daoism",               titleZh: "老子与道家",       dynasty: "E. Zhou",       cat: "culture",
    desc: "Laozi, legendary author of the Tao Te Ching, lives during this era. His philosophy of natural harmony and non-action (wu-wei) founds Daoism.",
    descZh: "传说中的老子著《道德经》，以「道」与「无为」为核心，开创了道家思想。" },
  { year: -496,  title: "Art of War Written",           titleZh: "《孙子兵法》成书", dynasty: "E. Zhou",       cat: "culture",
    desc: "Sunzi composes 'The Art of War', a 13-chapter military treatise still studied by strategists, business leaders, and generals worldwide.",
    descZh: "孙子著《孙子兵法》，此书共十三篇，至今仍是全球军事家与战略家的必读经典。" },
  { year: -403,  title: "Warring States Period Begins", titleZh: "战国时代开始",     dynasty: "E. Zhou",       cat: "political",
    desc: "The three-way partition of Jin is formally recognized, marking the Warring States era — seven major kingdoms in constant, devastating conflict.",
    descZh: "韩、赵、魏三家分晋获周天子承认，战国时代正式开始，七雄争霸，烽火连天。" },
  { year: -256,  title: "Zhou Dynasty Ends",            titleZh: "周朝灭亡",         dynasty: "E. Zhou",       cat: "political",
    desc: "The last Zhou king surrenders to Qin. The 800-year Zhou dynasty collapses, leaving Qin as the undisputed hegemon.",
    descZh: "最后一位周天子向秦国投降，绵延八百年的周朝就此终结，秦国独霸天下。" },
  { year: -221,  title: "Qin Unification",              titleZh: "秦统一六国",       dynasty: "Qin",           cat: "political",
    desc: "Ying Zheng conquers the last rival kingdom and declares himself 'Qin Shi Huang' — First Emperor of China — creating the first unified empire.",
    descZh: "嬴政灭六国，自称「秦始皇」，建立中国历史上第一个中央集权的统一帝国。" },
  { year: -215,  title: "Great Wall Construction",      titleZh: "修建长城",         dynasty: "Qin",           cat: "construction",
    desc: "Qin Shi Huang orders existing walls connected into one Great Wall using 300,000 soldiers and 500,000 laborers to defend against Xiongnu raids.",
    descZh: "秦始皇征调三十万将士与五十万民夫，将各段旧城墙连接为万里长城，以御匈奴。" },
  { year: -213,  title: "Burning of Books",             titleZh: "焚书坑儒",         dynasty: "Qin",           cat: "political",
    desc: "Chancellor Li Si advises burning Confucian and historical books outside the Qin canon, and burying 460 scholars alive, to suppress dissent.",
    descZh: "丞相李斯建议焚毁儒家典籍，并坑杀四百六十名儒士，以压制异见思想。" },
  { year: -210,  title: "Terracotta Army Completed",    titleZh: "兵马俑完工",       dynasty: "Qin",           cat: "construction",
    desc: "Qin Shi Huang's massive mausoleum complex, including 8,000 life-sized terracotta soldiers, chariots, and horses, is completed near Xi'an.",
    descZh: "秦始皇陵旁八千余件真人大小的陶制兵俑在骊山附近完工，气势震撼古今。" },
  { year: -209,  title: "Chen Sheng Uprising",          titleZh: "陈胜起义",         dynasty: "Qin",           cat: "military",
    desc: "Chen Sheng and Wu Guang lead China's first major peasant rebellion. Their uprising ignites the broader revolt that topples the Qin dynasty.",
    descZh: "陈胜、吴广发动中国历史上第一次大规模农民起义，引燃了推翻秦朝的熊熊烈火。" },
  { year: -206,  title: "Han Dynasty Founded",          titleZh: "汉朝建立",         dynasty: "W. Han",        cat: "political",
    desc: "Liu Bang defeats rival Xiang Yu and establishes the Han dynasty as Emperor Gaozu — the dynasty so foundational that Chinese people call themselves 'Han people'.",
    descZh: "刘邦击败项羽，建立汉朝，是为汉高祖。汉族之名，正源于此。" },
  { year: -138,  title: "Silk Road Opens",              titleZh: "丝绸之路开通",     dynasty: "W. Han",        cat: "trade",
    desc: "Emperor Wu sends diplomat Zhang Qian west, establishing the Silk Road — a network linking China to Central Asia, Persia, and Rome.",
    descZh: "汉武帝派遣张骞出使西域，开辟了连通中亚、波斯与罗马的丝绸之路。" },
  { year: -119,  title: "Han-Xiongnu Campaigns",        titleZh: "汉匈战争",         dynasty: "W. Han",        cat: "military",
    desc: "Generals Wei Qing and Huo Qubing lead massive campaigns deep into the Gobi, pushing the Xiongnu north and securing Han's northern frontier.",
    descZh: "卫青、霍去病率大军深入戈壁，重创匈奴，巩固了汉朝北部边疆。" },
  { year: -104,  title: "Shiji Completed",              titleZh: "《史记》完成",     dynasty: "W. Han",        cat: "culture",
    desc: "Sima Qian completes the Shiji (Records of the Grand Historian), China's first comprehensive history covering 2,500 years — written despite castration as punishment.",
    descZh: "司马迁身受宫刑后忍辱完成《史记》，记述两千五百年历史，是中国第一部纪传体通史。" },
  { year: 9,     title: "Wang Mang's Usurpation",       titleZh: "王莽篡汉",         dynasty: "Xin",           cat: "political",
    desc: "Wang Mang deposes the infant Han emperor and proclaims the Xin dynasty, attempting radical land redistribution and currency reform.",
    descZh: "王莽废黜幼帝，建立新朝，推行土地改革与货币改制，却引发大规模叛乱。" },
  { year: 105,   title: "Paper Invented",               titleZh: "蔡伦造纸",         dynasty: "E. Han",        cat: "invention",
    desc: "Cai Lun refines and standardizes papermaking from bark, hemp, and rags. Paper transforms communication, administration, and eventually global civilization.",
    descZh: "蔡伦改良造纸术，以树皮、麻布等为原料制成廉价纸张，深刻改变了人类的信息传播方式。" },
  { year: 132,   title: "Seismoscope Invented",         titleZh: "张衡发明地动仪",   dynasty: "E. Han",        cat: "invention",
    desc: "Zhang Heng invents the world's first seismoscope, capable of detecting distant earthquakes by dropping a bronze ball from a dragon's mouth.",
    descZh: "张衡发明世界上第一台地动仪，可通过青铜龙嘴落球感知远处地震。" },
  { year: 184,   title: "Yellow Turban Rebellion",      titleZh: "黄巾起义",         dynasty: "E. Han",        cat: "military",
    desc: "Daoist healer Zhang Jue leads a massive peasant uprising under the Yellow Turban banner, fatally weakening the Han and enabling warlord fragmentation.",
    descZh: "张角以黄巾为号领导大规模农民起义，沉重打击了东汉王朝，各地军阀乘乱割据。" },
  { year: 208,   title: "Battle of Red Cliffs",         titleZh: "赤壁之战",         dynasty: "E. Han",        cat: "military",
    desc: "Cao Cao's northern fleet is burned by Sun Quan and Liu Bei's allies in a decisive naval battle, ensuring the Three Kingdoms split and reshaping Chinese history.",
    descZh: "孙权、刘备联军火烧曹操水军，这场决定性的战役确立了三国鼎立的格局。" },
  { year: 220,   title: "Three Kingdoms Begin",         titleZh: "三国时代开始",     dynasty: "Wei",           cat: "political",
    desc: "Cao Pi deposes the last Han emperor and proclaims Wei. Liu Bei and Sun Quan soon follow, creating three rival kingdoms. The Romance of the Three Kingdoms immortalizes this era.",
    descZh: "曹丕废汉称帝，建立魏国。刘备与孙权随后称帝，三国鼎立正式形成，《三国演义》将这段历史传诵千古。" },
  { year: 265,   title: "Jin Reunification",            titleZh: "晋朝统一",         dynasty: "W. Jin",        cat: "political",
    desc: "Sima Yan founds the Jin dynasty and conquers Wu in 280, briefly reunifying China for the first time since Han.",
    descZh: "司马炎建立晋朝，280年灭吴，自汉末以来分裂多年的中国再度短暂统一。" },
  { year: 316,   title: "Northern China Falls",         titleZh: "北方沦陷",         dynasty: "N. Dynasties",  cat: "military",
    desc: "Xiongnu forces sack Luoyang and Chang'an. The Jin court flees south, beginning the Eastern Jin and nearly three centuries of north-south division.",
    descZh: "匈奴攻陷洛阳与长安，晋室南渡，北方陷入长达近三百年的分裂混战局面。" },
  { year: 399,   title: "Faxian's Pilgrimage to India", titleZh: "法显西行取经",     dynasty: "E. Jin",        cat: "culture",
    desc: "Monk Faxian walks overland to India and returns by sea to collect Buddhist scriptures — one of the most remarkable journeys of the ancient world.",
    descZh: "高僧法显徒步赴印度求取佛经，取海路归国，是古代世界最壮绝的旅行之一。" },
  { year: 494,   title: "N. Wei Sinicization Decree",  titleZh: "北魏汉化改革",     dynasty: "N. Dynasties",  cat: "political",
    desc: "Emperor Xiaowen of Northern Wei moves the capital to Luoyang and mandates Chinese dress, language, and names for the Xianbei — a landmark of cultural assimilation.",
    descZh: "北魏孝文帝迁都洛阳，强令鲜卑族改用汉语、汉服、汉姓，是民族融合的重要里程碑。" },
  { year: 581,   title: "Sui Reunification",            titleZh: "隋朝统一",         dynasty: "Sui",           cat: "political",
    desc: "Yang Jian (Emperor Wen) founds Sui and reunifies China for the first time in nearly 400 years, ending the north-south division.",
    descZh: "杨坚（隋文帝）建立隋朝，结束近四百年南北分裂局面，再次统一中国。" },
  { year: 605,   title: "Grand Canal Built",            titleZh: "大运河修建",       dynasty: "Sui",           cat: "construction",
    desc: "Emperor Yang orders the Grand Canal, linking the Yellow and Yangtze rivers over 1,700 km. Over a million laborers were conscripted. Still in use today.",
    descZh: "隋炀帝征发百余万民夫，开凿全长一千七百公里的大运河，贯通南北，沿用至今。" },
  { year: 612,   title: "Goguryeo Campaign Fails",      titleZh: "征高句丽失败",     dynasty: "Sui",           cat: "military",
    desc: "Sui's catastrophic invasion of the Korean kingdom of Goguryeo. Over a million soldiers mobilized; massive defeat triggers rebellions that destroy the dynasty.",
    descZh: "隋炀帝三征高句丽，百万大军折损殆尽，惨败引发各地叛乱，加速了隋朝的覆灭。" },
  { year: 618,   title: "Tang Dynasty Founded",         titleZh: "唐朝建立",         dynasty: "Tang",          cat: "political",
    desc: "Li Yuan, Duke of Tang, overthrows the Sui as Emperor Gaozu. His son Li Shimin (Emperor Taizong) soon creates one of China's greatest reigns.",
    descZh: "李渊（唐高祖）推翻隋朝，建立唐朝。其子李世民（唐太宗）开创贞观之治，奠定盛唐基础。" },
  { year: 629,   title: "Xuanzang's Journey to India",  titleZh: "玄奘西游取经",     dynasty: "Tang",          cat: "culture",
    desc: "Monk Xuanzang travels secretly overland to India for Buddhist scriptures, returning after 17 years. His journey inspired the classic novel Journey to the West.",
    descZh: "高僧玄奘秘密出境赴印度求取佛经，十七年后载誉归来，其传奇经历催生了名著《西游记》。" },
  { year: 690,   title: "Empress Wu Zetian",            titleZh: "武则天称帝",       dynasty: "Tang",          cat: "political",
    desc: "Wu Zetian declares herself Emperor of the Zhou — the only woman in Chinese history to assume the title of empress regnant, ruling effectively for decades.",
    descZh: "武则天改国号为周，登基称帝，成为中国历史上唯一正式称皇帝的女性，实际掌权数十年。" },
  { year: 751,   title: "Battle of Talas",              titleZh: "怛罗斯之战",       dynasty: "Tang",          cat: "military",
    desc: "Tang forces defeated by the Abbasid Caliphate at Talas River. Captured Tang soldiers transmit papermaking technology to the Islamic world and eventually Europe.",
    descZh: "唐军败于阿拔斯王朝，被俘的唐朝工匠将造纸术传入伊斯兰世界，进而传至欧洲。" },
  { year: 755,   title: "An Lushan Rebellion",          titleZh: "安史之乱",         dynasty: "Tang",          cat: "military",
    desc: "General An Lushan rebels and sacks Chang'an. The devastating eight-year war kills tens of millions and the Tang never fully recovers its former glory.",
    descZh: "安禄山起兵叛唐，攻陷长安。这场历时八年的战乱造成数千万人死亡，唐朝从此由盛转衰。" },
  { year: 868,   title: "Diamond Sutra Printed",        titleZh: "金刚经印刷",       dynasty: "Tang",          cat: "culture",
    desc: "The Diamond Sutra (868 CE) is printed using woodblock printing — the oldest dated printed book in existence, discovered in the Dunhuang cave manuscripts.",
    descZh: "《金刚经》以雕版印刷完成，是现存世界上最早有明确纪年的印刷书籍，出土于敦煌莫高窟。" },
  { year: 907,   title: "Tang Falls",                   titleZh: "唐朝灭亡",         dynasty: "5 Dynasties",   cat: "political",
    desc: "Warlord Zhu Wen deposes the last Tang emperor. China fragments into the Five Dynasties in the north and Ten Kingdoms in the south for 53 years.",
    descZh: "朱温废唐称帝，中国进入五代十国的乱世，北方五朝迭代，南方十国割据，分裂长达五十三年。" },
  { year: 960,   title: "Song Dynasty Founded",         titleZh: "宋朝建立",         dynasty: "N. Song",       cat: "political",
    desc: "General Zhao Kuangyin is acclaimed emperor by his soldiers in the 'Yellow Robe Incident', founding the Song dynasty through a near-bloodless coup.",
    descZh: "赵匡胤在「陈桥兵变」中被部将黄袍加身，几乎兵不血刃地建立宋朝。" },
  { year: 1040,  title: "Movable Type Invented",        titleZh: "毕昇发明活字印刷", dynasty: "N. Song",       cat: "invention",
    desc: "Bi Sheng invents movable type printing with fired ceramic characters — four centuries before Gutenberg, transforming the spread of knowledge in East Asia.",
    descZh: "毕昇发明泥活字印刷术，比古腾堡早约四百年，极大推动了东亚知识的传播。" },
  { year: 1069,  title: "Wang Anshi's New Policies",    titleZh: "王安石变法",       dynasty: "N. Song",       cat: "political",
    desc: "Grand Chancellor Wang Anshi implements sweeping fiscal, military, and agricultural reforms, sparking one of China's most intense political factional battles.",
    descZh: "宰相王安石推行财政、军事与农业改革，引发了北宋历史上最激烈的政治派系之争。" },
  { year: 1115,  title: "Jin Dynasty Founded",          titleZh: "金朝建立",         dynasty: "Jin (Jurchen)", cat: "political",
    desc: "Wanyan Aguda unites the Jurchen tribes and founds the Jin dynasty, beginning their conquest of the Liao and eventual takeover of northern China.",
    descZh: "完颜阿骨打统一女真各部，建立金国，随后灭辽、攻宋，占领中国北方。" },
  { year: 1127,  title: "Fall of Northern Song",        titleZh: "北宋灭亡",         dynasty: "S. Song",       cat: "military",
    desc: "Jin forces capture the Song capital Kaifeng and take Emperor Huizong and Emperor Qinzong prisoner. The 'Jingkang Incident' — the Song court's greatest humiliation.",
    descZh: "金军攻陷汴京，掳走宋徽宗、宋钦宗，史称「靖康之耻」，北宋就此覆灭。" },
  { year: 1215,  title: "Mongols Take Beijing",         titleZh: "蒙古攻占北京",     dynasty: "Jin (Jurchen)", cat: "military",
    desc: "Genghis Khan's forces sack Zhongdu (Beijing) after a long siege, dealing a devastating blow to the Jurchen Jin dynasty.",
    descZh: "成吉思汗攻陷金国中都（今北京），女真金朝元气大伤。" },
  { year: 1271,  title: "Yuan Dynasty Founded",         titleZh: "元朝建立",         dynasty: "Yuan",          cat: "political",
    desc: "Kublai Khan renames the Mongol domain 'Yuan', establishing a Chinese-style dynasty while ruling from Khanbaliq (Beijing).",
    descZh: "忽必烈将蒙古政权改国号为「元」，建立汉式王朝，定都大都（今北京）。" },
  { year: 1275,  title: "Marco Polo Arrives",           titleZh: "马可·波罗来华",    dynasty: "Yuan",          cat: "trade",
    desc: "Venetian merchant Marco Polo arrives at Kublai Khan's court and spends 17 years in China. His later accounts introduce a dazzling China to medieval Europe.",
    descZh: "威尼斯商人马可·波罗抵达忽必烈宫廷，在华旅居十七年，其游记让神秘的中国震惊了中世纪欧洲。" },
  { year: 1279,  title: "Mongol Conquest Complete",     titleZh: "蒙古统一全国",     dynasty: "Yuan",          cat: "military",
    desc: "Battle of Yamen: the last Song loyalists are crushed. Prime Minister Lu Xiufu leaps into the sea carrying the child emperor. China is fully under Mongol rule.",
    descZh: "崖山海战，末代南宋小皇帝被丞相陆秀夫抱入海中殉国，中国全境纳入蒙古统治。" },
  { year: 1351,  title: "Red Turban Rebellion",         titleZh: "红巾军起义",       dynasty: "Yuan",          cat: "military",
    desc: "White Lotus Society uprising against Mongol rule. Zhu Yuanzhang, a peasant orphan turned monk, rises to lead the rebellion that founds the Ming.",
    descZh: "白莲教发动反元起义，穷苦孤儿出身的朱元璋在乱世中脱颖而出，最终建立明朝。" },
  { year: 1368,  title: "Ming Dynasty Founded",         titleZh: "明朝建立",         dynasty: "Ming",          cat: "political",
    desc: "Zhu Yuanzhang expels the Mongols and founds the Ming dynasty as the Hongwu Emperor, rising from abject poverty to rule the world's largest empire.",
    descZh: "朱元璋驱逐蒙古人，建立明朝，是为洪武帝，从一介贫民到天下之主，堪称传奇。" },
  { year: 1405,  title: "Zheng He's Voyages Begin",     titleZh: "郑和下西洋",       dynasty: "Ming",          cat: "trade",
    desc: "Admiral Zheng He leads the first of seven massive treasure fleet expeditions, reaching Southeast Asia, India, Arabia, and East Africa with ships dwarfing Columbus's.",
    descZh: "郑和率领庞大船队七下西洋，远抵东南亚、印度、阿拉伯和东非，舰船规模远超哥伦布船队。" },
  { year: 1420,  title: "Forbidden City Completed",     titleZh: "紫禁城落成",       dynasty: "Ming",          cat: "construction",
    desc: "The Forbidden City (Palace Museum) in Beijing is completed after 14 years of construction using a million laborers. It served as the imperial palace for 500 years.",
    descZh: "征发百万民夫历时十四年修建的紫禁城竣工，此后五百年间一直是皇家宫殿。" },
  { year: 1449,  title: "Tumu Crisis",                  titleZh: "土木堡之变",       dynasty: "Ming",          cat: "military",
    desc: "Emperor Zhengtong is captured by Oirat Mongols at Tumu — an emperor taken prisoner in battle. The court crowns a new emperor and successfully defends Beijing.",
    descZh: "明英宗在土木堡被瓦剌俘虏，朝廷随即另立新君，成功击退瓦剌军队。" },
  { year: 1582,  title: "Matteo Ricci in China",        titleZh: "利玛窦来华",       dynasty: "Ming",          cat: "culture",
    desc: "Jesuit missionary Matteo Ricci arrives in China, mastering classical Chinese and eventually gaining access to the imperial court, beginning a major cultural exchange.",
    descZh: "耶稣会士利玛窦来华，精通汉语经典，最终获准觐见皇帝，开启中西文化交流的新篇章。" },
  { year: 1644,  title: "Fall of Ming / Qing Conquest", titleZh: "明朝灭亡 / 清朝入关", dynasty: "Qing",       cat: "political",
    desc: "Rebel Li Zicheng captures Beijing; Emperor Chongzhen hangs himself. Manchu forces enter through the Great Wall and establish the Qing dynasty.",
    descZh: "李自成攻陷北京，崇祯帝自缢殉国，清军入关建立清朝。" },
  { year: 1661,  title: "Kangxi Emperor's Reign",       titleZh: "康熙帝登基",       dynasty: "Qing",          cat: "political",
    desc: "The Kangxi Emperor begins his 61-year reign — the longest confirmed reign of any Chinese emperor — marked by military campaigns and the great Kangxi Dictionary.",
    descZh: "康熙帝开始长达六十一年的统治，是中国历史上在位时间最长的皇帝，以武功赫赫与编纂《康熙字典》著称。" },
  { year: 1683,  title: "Taiwan Annexed",               titleZh: "台湾纳入版图",     dynasty: "Qing",          cat: "political",
    desc: "Qing forces defeat the Ming loyalist Kingdom of Tungning, bringing Taiwan under Chinese imperial control for the first time in history.",
    descZh: "清军击败明郑政权，台湾首次纳入中国王朝的直接管辖。" },
  { year: 1793,  title: "Macartney Mission Rejected",   titleZh: "马戛尔尼使团被拒", dynasty: "Qing",          cat: "trade",
    desc: "British envoy Macartney seeks expanded trade; Emperor Qianlong famously replies that China 'possesses all things' and has no need for foreign goods.",
    descZh: "英使马戛尔尼请求扩大通商，乾隆帝以「天朝物产丰盈」为由拒绝，成为闭关锁国的象征。" },
  { year: 1839,  title: "First Opium War",              titleZh: "第一次鸦片战争",   dynasty: "Qing",          cat: "military",
    desc: "Commissioner Lin Zexu destroys 1,200 tons of British opium. Britain retaliates militarily, beginning the 'Century of Humiliation' and the era of unequal treaties.",
    descZh: "林则徐销毁英国鸦片，英国以武力回应，「百年屈辱」由此开始，不平等条约接踵而来。" },
  { year: 1842,  title: "Treaty of Nanking",            titleZh: "南京条约签订",     dynasty: "Qing",          cat: "political",
    desc: "China's first 'unequal treaty' cedes Hong Kong Island to Britain and opens five treaty ports. The model for a series of humiliating concessions to follow.",
    descZh: "中国签订第一个不平等条约，割让香港岛，开放五口通商，开此后一系列丧权辱国之先河。" },
  { year: 1850,  title: "Taiping Heavenly Kingdom",     titleZh: "太平天国运动",     dynasty: "Qing",          cat: "military",
    desc: "Hong Xiuquan, who believed himself Jesus's younger brother, establishes a Christian theocracy in southern China. The ensuing war kills 20–30 million people.",
    descZh: "自称耶稣之弟的洪秀全在南方建立太平天国，随后的战争造成二三千万人死亡。" },
  { year: 1860,  title: "Old Summer Palace Burned",     titleZh: "圆明园被焚",       dynasty: "Qing",          cat: "military",
    desc: "Anglo-French forces burn and loot the Old Summer Palace (Yuanmingyuan) during the Second Opium War. The ruins remain a symbol of national humiliation.",
    descZh: "第二次鸦片战争中英法联军焚毁并洗劫圆明园，废墟至今是民族屈辱的象征。" },
  { year: 1894,  title: "First Sino-Japanese War",      titleZh: "甲午战争",         dynasty: "Qing",          cat: "military",
    desc: "China is decisively defeated by Meiji Japan, ceding Taiwan and paying massive reparations. The defeat shocks China and accelerates reform movements.",
    descZh: "中国在甲午战争中惨败于日本，被迫割让台湾并赔付巨额赔款，举国震惊，变法呼声高涨。" },
  { year: 1898,  title: "Hundred Days Reform",          titleZh: "戊戌变法",         dynasty: "Qing",          cat: "political",
    desc: "Emperor Guangxu issues sweeping modernization edicts. Empress Dowager Cixi stages a coup after 103 days, imprisoning him and executing reformers.",
    descZh: "光绪帝颁布一系列维新变法诏书，百日后遭慈禧太后政变推翻，光绪被囚，变法人士被杀。" },
  { year: 1900,  title: "Boxer Rebellion",              titleZh: "义和团运动",       dynasty: "Qing",          cat: "military",
    desc: "Anti-foreign Boxer uprising supported by Empress Dowager Cixi. Eight-nation alliance invades, occupies Beijing, and forces the Boxer Protocol — another humiliation.",
    descZh: "义和团排外运动得到慈禧支持，八国联军入侵并占领北京，《辛丑条约》再次丧权辱国。" },
  { year: 1905,  title: "Imperial Exam Abolished",      titleZh: "废除科举制度",     dynasty: "Qing",          cat: "political",
    desc: "The 1,300-year-old imperial examination system is abolished. The backbone of China's civil service and Confucian social order disappears overnight.",
    descZh: "延续一千三百年的科举制度废除，儒家社会秩序的基石一夜之间轰然倒塌。" },
  { year: 1911,  title: "Xinhai Revolution",            titleZh: "辛亥革命",         dynasty: "ROC",           cat: "political",
    desc: "The Wuchang Uprising triggers nationwide revolt. Sun Yat-sen is proclaimed provisional president; provinces declare independence and the Qing dynasty collapses.",
    descZh: "武昌起义引发全国响应，孙中山被推举为临时大总统，各省宣布独立，清朝土崩瓦解。" },
  { year: 1912,  title: "Republic Founded",             titleZh: "中华民国成立",     dynasty: "ROC",           cat: "political",
    desc: "The Republic of China is proclaimed on January 1. Last emperor Puyi abdicates on February 12, ending over 2,000 years of imperial rule.",
    descZh: "中华民国于1月1日宣告成立，末代皇帝溥仪于2月12日退位，延续两千余年的帝制就此终结。" },
  { year: 1919,  title: "May Fourth Movement",          titleZh: "五四运动",         dynasty: "ROC",           cat: "culture",
    desc: "Student protests against the Versailles Treaty spark a sweeping cultural revolution: rejection of Confucian tradition, embrace of science, democracy, and vernacular literature.",
    descZh: "学生抗议《凡尔赛条约》引发广泛的文化革命，儒家传统受到冲击，科学与民主的呼声高涨。" },
  { year: 1921,  title: "CCP Founded",                  titleZh: "中国共产党成立",   dynasty: "ROC",           cat: "political",
    desc: "The Chinese Communist Party is founded in Shanghai with 13 delegates, including a young Mao Zedong. Chen Duxiu becomes first General Secretary.",
    descZh: "中国共产党在上海秘密成立，与会代表十三人，年轻的毛泽东亦在其中。" },
  { year: 1927,  title: "Shanghai Massacre",            titleZh: "上海四一二事变",   dynasty: "ROC",           cat: "political",
    desc: "Chiang Kai-shek's Nationalists massacre thousands of Communist Party members in Shanghai, permanently fracturing the first United Front and starting the Civil War.",
    descZh: "蒋介石在上海大规模屠杀共产党人，国共第一次合作彻底破裂，内战就此开始。" },
  { year: 1931,  title: "Japan Invades Manchuria",      titleZh: "九一八事变",       dynasty: "ROC",           cat: "military",
    desc: "The Mukden Incident: Japanese officers blow up their own railway to justify invading Manchuria, establishing the Manchukuo puppet state.",
    descZh: "日本军官自导自演炸毁铁路，以此为借口占领东北，扶植满洲国傀儡政权。" },
  { year: 1934,  title: "The Long March",               titleZh: "长征",             dynasty: "ROC",           cat: "military",
    desc: "Communist forces make an epic 6,000-mile retreat across China to escape Nationalist encirclement. Mao Zedong emerges as undisputed leader of the CCP.",
    descZh: "共产党军队在国军围剿下被迫进行两万五千里长征，毛泽东在长征中确立了对党的领导权。" },
  { year: 1937,  title: "Second Sino-Japanese War",     titleZh: "抗日战争爆发",     dynasty: "ROC",           cat: "military",
    desc: "Full-scale Japanese invasion begins. The Nanjing Massacre kills an estimated 200,000–300,000 civilians and POWs. China endures eight years of brutal occupation.",
    descZh: "日本发动全面侵华战争，南京大屠杀中约二三十万平民与战俘惨遭杀害，中国遭受八年浩劫。" },
  { year: 1945,  title: "Japan Surrenders",             titleZh: "日本投降",         dynasty: "ROC",           cat: "military",
    desc: "Japan surrenders following the atomic bombs and Soviet entry into the Pacific War. Taiwan returns to Chinese control after 50 years of Japanese colonial rule.",
    descZh: "原子弹轰炸与苏联出兵后，日本宣布投降，阔别五十年的台湾重回中国版图。" },
  { year: 1949,  title: "PRC Founded",                  titleZh: "中华人民共和国成立", dynasty: "PRC",         cat: "political",
    desc: "Mao Zedong proclaims the People's Republic of China from Tiananmen Gate on October 1. The Nationalist government retreats to Taiwan.",
    descZh: "毛泽东于天安门城楼上宣告中华人民共和国成立，国民政府随即撤退台湾。" },
  { year: 1950,  title: "Korean War Entry",             titleZh: "参加朝鲜战争",     dynasty: "PRC",           cat: "military",
    desc: "China sends 'volunteer' forces to Korea, pushing UN forces back from the Yalu River in a surprising display of military power. Over 180,000 Chinese casualties.",
    descZh: "中国出动「志愿军」赴朝参战，将联合国军从鸭绿江边击退，伤亡逾十八万。" },
  { year: 1958,  title: "Great Leap Forward",           titleZh: "大跃进",           dynasty: "PRC",           cat: "political",
    desc: "Mao's rapid industrialization and collectivization campaign causes the Great Chinese Famine — historians estimate 15–55 million deaths from starvation.",
    descZh: "毛泽东强行推进工业化与集体化，引发大规模饥荒，历史学家估计饿死人数达一千五百万至五千五百万。" },
  { year: 1964,  title: "China Tests Nuclear Bomb",     titleZh: "中国核试验",       dynasty: "PRC",           cat: "political",
    desc: "China's first successful nuclear weapons test makes it the fifth nuclear power, dramatically altering the Cold War balance of power in Asia.",
    descZh: "中国第一颗原子弹试爆成功，成为第五个拥核国家，深刻改变了亚洲冷战格局。" },
  { year: 1966,  title: "Cultural Revolution Begins",   titleZh: "文化大革命开始",   dynasty: "PRC",           cat: "political",
    desc: "Mao launches the Cultural Revolution to purge rivals and reassert control. Red Guards destroy temples, artworks, and persecute millions of intellectuals.",
    descZh: "毛泽东发动文化大革命以清洗政敌，红卫兵捣毁寺庙文物，数百万知识分子遭受迫害。" },
  { year: 1972,  title: "Nixon Visits China",           titleZh: "尼克松访华",       dynasty: "PRC",           cat: "trade",
    desc: "US President Nixon's historic week-long visit ends 23 years of estrangement and reshapes Cold War geopolitics, isolating the Soviet Union.",
    descZh: "美国总统尼克松历史性访华，结束中美长达二十三年的对立，深刻改变冷战格局，孤立了苏联。" },
  { year: 1976,  title: "Mao Zedong Dies",              titleZh: "毛泽东逝世",       dynasty: "PRC",           cat: "political",
    desc: "Mao dies at 82. Hua Guofeng arrests the Gang of Four within weeks. Deng Xiaoping gradually rises to power, pivoting China toward pragmatic reform.",
    descZh: "毛泽东以八十二岁高龄辞世，华国锋随即逮捕「四人帮」，邓小平逐步崛起，开启改革新时代。" },
  { year: 1978,  title: "Reform & Opening Up",          titleZh: "改革开放",         dynasty: "PRC",           cat: "political",
    desc: "Deng Xiaoping launches market reforms and creates Special Economic Zones. China begins its transformation from a closed communist state into an economic powerhouse.",
    descZh: "邓小平推行市场化改革，设立经济特区，中国由封闭的计划经济体制向经济强国转变。" },
  { year: 1989,  title: "Tiananmen Square",             titleZh: "天安门事件",       dynasty: "PRC",           cat: "political",
    desc: "Student-led democracy protests gather in Beijing and dozens of cities. Military crackdown on June 4th kills hundreds to thousands and reshapes China's political trajectory.",
    descZh: "学生主导的民主运动席卷北京及数十座城市，六四军事镇压造成数百至数千人死亡，深刻影响了中国的政治走向。" },
  { year: 1997,  title: "Hong Kong Handover",           titleZh: "香港回归",         dynasty: "PRC",           cat: "political",
    desc: "Britain transfers Hong Kong to China under 'one country, two systems', ending 156 years of British colonial rule. Macau follows in 1999.",
    descZh: "英国将香港主权移交中国，以「一国两制」为框架，结束了长达一百五十六年的英国殖民统治。" },
  { year: 2001,  title: "China Joins WTO",              titleZh: "中国加入世贸组织", dynasty: "PRC",           cat: "trade",
    desc: "China joins the World Trade Organization, accelerating its integration into the global economy and triggering the most rapid economic expansion in history.",
    descZh: "中国正式加入世界贸易组织，加速融入全球经济，推动了人类历史上最快速的经济腾飞。" },
  { year: 2008,  title: "Beijing Olympics",             titleZh: "北京奥运会",       dynasty: "PRC",           cat: "culture",
    desc: "China hosts the Summer Olympics with a spectacular opening ceremony watched by 1 billion people, announcing its emergence as a global superpower.",
    descZh: "中国举办夏季奥运会，盛大的开幕式吸引全球十亿人收看，向世界宣示中国的强势崛起。" },
  { year: 2013,  title: "Belt & Road Initiative",       titleZh: "一带一路",         dynasty: "PRC",           cat: "trade",
    desc: "Xi Jinping announces the Belt and Road Initiative — a trillion-dollar global infrastructure investment program spanning 140+ countries, reviving the ancient Silk Road concept.",
    descZh: "习近平宣布「一带一路」倡议，这一涉及一百四十余国的全球基础设施投资计划，重振了古代丝绸之路的精神。" },
  { year: 2020,  title: "COVID-19 Pandemic",            titleZh: "新冠疫情",         dynasty: "PRC",           cat: "political",
    desc: "COVID-19 emerges in Wuhan and spreads to become the worst global pandemic since 1918. China implements strict lockdowns; global death toll exceeds 7 million.",
    descZh: "新冠病毒首发于武汉，迅速演变为1918年以来最严重的全球大流行病，全球死亡人数超过七百万。" },
];
